/** @type {import('tailwindcss').Config} */
module.exports = {

  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],

  theme: {
    colors: {
      header_icon:" #F9E66E",
      header_col: "#7A6DE6",
      header_btn: "#F4BF4E",
      select_col: "#58B6EF",
      white: "#FFFFFF",
      black: "#000000",
      silver: "#CCCCCC",
      pink: "#BA99F5",
      gray: "#696969",
      yellow: "#FAE76F",
      blue: "rgb(0, 0, 255)",
      bluee: "#68BCF8",
      transparent: "transparent",
      chest1_color: "#FC92F1",
      chest2_color: "#8FD1FA",
      chest3_color: "#7EF389;",
      chest4_color: " #FAE76F;",
      chest5_color: "#FB72FE;",
      price:"#D9D9D9",
      light_pink: "#FFCBFF",
      silver1:"#E2E8EA",
      purple:" #ADADF4",
      purple1: "#6666CA",
      blue3:"#94CEF1",
      yellow1:"rgba(246, 232, 53, 1)",
      grey1:"rgba(254, 254, 146, 1)",
      footer_col:"#978BF5",
      steptwo_col:"rgba(139, 151, 255, 1)"
    },

    extend: {
      backgroundImage: {
        flag1: "url('../images/flag1.png')",
        search: "url('../images/search.png')",
        next_btn:"url('../images/step.png')",
        snduk1:"url('../images/snduk1.png')",
        snduk2:"url('../images/snduk2.png')",
        snduk3:"url('../images/snduk3.png')",
        snduk4:"url('../images/snduk4.png')",
        snduk5:"url('../images/snduk5.png')",
        flag2: "url('../images/flag2.png')",
        draft11: "url('../images/draft11.png')",
        draft2: "url('../images/draft2.png')",
        draft3: "url('../images/draft3.png')",
        draft4: "url('../images/draft4.png')",
        flag3: "url('../images/flag3.png')",
        swords: "url('../images/swords.png')",
        flag4: "url('../images/flag4.png')",
        button1: "url('../images/button1.png')",
        button2: "url('../images/button2.png')",
        arrow: "url('../images/downArrow.png')",
        logo: "url('../images/logo.png')",
        oclock:"url('../images/oclock.png')",
        snduk6:"url('../images/snduk6.png')",
        family:"url('../images/family.png')",
        level:"url('../images/level.png')",
        logo1: "url('../images/logo1.png')",
        logo_1: "url('../images/logo_1.png')",
        logo2: "url('../images/logo2.png')",
        logo3: "url('../images/logo3.png')",
        logo4: "url('../images/logo4.png')",
        logo5: "url('../images/logo5.png')",
        logo6: "url('../images/logo6.png')",
        logo7: "url('../images/logo7.png')",
        logo8: "url('../images/logo8.png')",
        link1:"url('../images/link1.png')",
        link2:"url('../images/link2.png')",
        link3:"url('../images/link3.png')",
        link4:"url('../images/link4.png')",
        link5:"url('../images/link5.png')",
        link6:"url('../images/link6.png')",
        locatia:"url('../images/locatia.png')",
        message:"url('../images/message.png')",
        select:"url('../images/select.png')",
        vector:"url('../images/vector.png')",
        vector1:"url('../images/vector1.png')",
        share:"url('../images/share.png')",
        star: "url('../images/star.png')",
        yellowStar:"url('../images/yellowStar.png')",
        file:"url('../images/file.png')",
        vector2:"url('../images/vector2.png')",
        union:"url('../images/union.png')",
        down:"url('../images/down.png')",
        btn_3:"url('../images/step3_btn.png')"
        },
    },

    fontFamily: {
      kanit: "Kanit",
    },

    clipPath: {
      mypolygon: "polygon(0% 0%, 83% 0, 100% 50%, 83% 100%, 0% 100%)",
      mypoligon2: "polygon(85% 0%, 100% 50%, 85% 100%, 0% 100%, 15% 50%, 0% 0%)",
      mypoligon3: "polygon(100% 0, 100% 50%, 100% 100%, 0 100%, 15% 50%, 0% 0%)",
      triangle: "polygon(100% 0, 0 50%, 100% 100%)"
    },

  },
  plugins: [
    require('tailwind-clip-path'),
  ],
}
